apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        # Образ ClickHouse с возможностью указания версии из параметра
        image: clickhouse/clickhouse-server:{{ .Values.image.tag }}
        ports:
        - containerPort: 8123 # HTTP интерфейс
          name: http
        - containerPort: 9000 # Native TCP интерфейс
          name: native
        env:
        # Параметры для пользователей задаются через конфиг или env
        - name: CLICKHOUSE_USER_LIST
          valueFrom:
            configMapKeyRef:
              name: clickhouse-users
              key: user-list
        - name: CLICKHOUSE_PASSWORD_LIST
          valueFrom:
            secretKeyRef:
              name: clickhouse-passwords
              key: password-list
        volumeMounts:
        - name: config-volume
          mountPath: /etc/clickhouse-server/config.xml
          subPath: config.xml
        - name: config-volume
          mountPath: /etc/clickhouse-server/users.xml
          subPath: users.xml
      volumes:
      - name: config-volume
        configMap:
          name: clickhouse-config
